website_scraping_task:
  description: >
    Analyze the website at {website_url} and generate a description and metadata.
  expected_output: >
    A markdown file with a few sentence description of the website from this website url: {website_url}
    , what the business does, and a JSON mapping of the business name and url where the JSON is formatted
    within the markdown file
  agent: website_scraper

industry_task:
  description: >
    Review the context received and provide the best NAICs industry and its associated 
    code to go with the given context
  expected_output: >
    From the previous report, retain all previous data, including the description of the restaurant.
    Make sure the title of the report is the name of the restaurant. Underneath the title
    add the description of the business. At the bottom, in JSON format, make sure all previous JSON
    data is included and add the key value pairs to it for the NAICs industry name and
    the corresponding code with their own key value pair.
  agent: industry_analyst
